//! Exact ProofPlan validation and per-column provenance for recorded witnesses.
//!
//! Canonical host construction stays beside the generated lane specs in
//! `stwo-cairo-prover`. Generator-fed columns that do not exist pre-witness are
//! never zero-filled: each is either a mechanically resolved producer edge or an
//! explicit unresolved column that keeps strict Graph-A admission fail-closed.

use std::sync::Arc;

use stwo_cairo_adapter::memory::Memory;
use stwo_cairo_prover::witness::cairo_claim_generator::CairoClaimGenerator;
use stwo_cairo_prover::witness::jit_prove_backend::{
    recorded_input_compaction_geometry, recorded_input_geometry, recorded_witness_input_attempt,
    ExecutionMemoryIdentity, RecordedInputBuildError, RecordedTableIdentity,
    RecordedWitnessInputSource, RecordedWitnessInputsError,
};
use stwo_cairo_prover::witness::proof_shape::{RowResolution, TracePartId};

use crate::plan::ProofPlan;
use crate::schedule::{ComponentId, ComponentNode, InputEdge, WitnessWriterKind};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DeviceEdgeSourceKind {
    SubcomponentWords,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DeviceEdgeColumn {
    pub producer: ComponentId,
    pub source_kind: DeviceEdgeSourceKind,
    /// Word within each producer instance; the gather repeats this ordinal over
    /// `n_instances` before flattening to the consumer column.
    pub source_word: u32,
    pub words_per_instance: u32,
    pub n_instances: u32,
}

/// One output column of the prepared ordered multi-producer gather. Data edges
/// are in the exact append order of the legacy `Mutex<Vec<_>>` consumer; the
/// mechanical tail is generated by the same capture-safe kernel.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum DeviceGatherColumn {
    Data { edges: Vec<DeviceEdgeColumn> },
    Enabler,
    Iota,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum UnresolvedColumnReason {
    NoProducerEdge,
    ProducerEdgesRequireCompaction {
        producer_count: usize,
    },
    ProducerEdgeGeometryMismatch {
        producer_words: usize,
        consumer_data_columns: usize,
    },
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct UnresolvedInputColumn {
    pub component: ComponentId,
    pub ordinal: usize,
    pub reason: UnresolvedColumnReason,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum RecordedInputColumnProvenance {
    Host(Vec<u32>),
    DeviceNative(DeviceNativeColumn),
    DeviceSeed(DeviceSeedColumn),
    DeviceEdge(DeviceEdgeColumn),
    DeviceGather(DeviceGatherColumn),
    DeviceCompact(DeviceCompactColumn),
    Unresolved(UnresolvedInputColumn),
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DeviceNativeColumn {
    pub producer: ComponentId,
    pub ordinal: usize,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum DeviceSeedColumn {
    Scalar { index: usize, value: u32 },
    Enabler,
    Iota,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DeviceCompactColumn {
    Tuple { word: usize },
    Enabler,
    Iota,
    Multiplicity,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PlannedRecordedWitnessInput {
    pub component: ComponentId,
    pub program: stwo_backend_cuda::jit_witness::isa::WitnessProgram,
    pub row_count: usize,
    pub n_real: usize,
    pub columns: Vec<RecordedInputColumnProvenance>,
    pub tables: RecordedTableIdentity,
    /// Why canonical host columns were unavailable. Device-edge resolution may
    /// still cover every column; unresolved columns always remain explicit.
    pub host_build_error: Option<RecordedInputBuildError>,
}

impl PlannedRecordedWitnessInput {
    pub fn unresolved_ordinals(&self) -> Vec<usize> {
        self.columns
            .iter()
            .enumerate()
            .filter_map(|(ordinal, source)| {
                matches!(source, RecordedInputColumnProvenance::Unresolved(_)).then_some(ordinal)
            })
            .collect()
    }
}

#[derive(Clone, Debug)]
pub struct PlannedRecordedWitnessInputs {
    pub execution_memory: Arc<Memory>,
    pub execution_memory_identity: ExecutionMemoryIdentity,
    pub lanes: Vec<PlannedRecordedWitnessInput>,
}

impl PlannedRecordedWitnessInputs {
    pub fn unresolved_columns(&self) -> Vec<(ComponentId, usize)> {
        self.lanes
            .iter()
            .flat_map(|lane| {
                lane.unresolved_ordinals()
                    .into_iter()
                    .map(|ordinal| (lane.component, ordinal))
            })
            .collect()
    }

    pub fn require_resolved(&self) -> Result<(), RecordedWitnessPlanError> {
        let unresolved = self.unresolved_columns();
        if unresolved.is_empty() {
            Ok(())
        } else {
            Err(RecordedWitnessPlanError::UnresolvedColumns(unresolved))
        }
    }
}

#[derive(Debug)]
pub enum RecordedWitnessPlanError {
    Inputs(RecordedWitnessInputsError),
    ShapeNotExact(ComponentId),
    InvalidTracePart(ComponentId),
    /// The witness dependency graph could not be topologically ordered
    /// (cyclic or dangling producer edges).
    UnorderableSchedule,
    RowGeometryMismatch {
        component: ComponentId,
        expected_real: usize,
        actual_real: usize,
        expected_padded: usize,
        actual_padded: usize,
    },
    UnsupportedLabels(Vec<ComponentId>),
    UnresolvedColumns(Vec<(ComponentId, usize)>),
    InputBuild {
        component: ComponentId,
        source: RecordedInputBuildError,
    },
    MissingInputGeometry(ComponentId),
    SizeOverflow(ComponentId),
}

impl core::fmt::Display for RecordedWitnessPlanError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "recorded witness ProofPlan rejected: {self:?}")
    }
}

impl std::error::Error for RecordedWitnessPlanError {}

impl From<RecordedWitnessInputsError> for RecordedWitnessPlanError {
    fn from(value: RecordedWitnessInputsError) -> Self {
        Self::Inputs(value)
    }
}

struct ExpectedLane {
    node: &'static ComponentNode,
    n_real: usize,
    row_count: usize,
}

/// Build one provenance-complete entry for every present RecordedAot component.
/// Host columns are exact recorder slots; direct producer columns are semantic
/// device-edge aliases; every remaining column is explicitly unresolved.
pub fn recorded_witness_inputs_for_plan(
    generator: &CairoClaimGenerator,
    proof_plan: &ProofPlan,
) -> Result<PlannedRecordedWitnessInputs, RecordedWitnessPlanError> {
    // Lanes must be planned in the same topological (producer-before-consumer)
    // order the arena witness workspace and the Graph A launcher use; the
    // resident session zips the two lists pairwise and fails closed on any
    // order drift. Plan order differs whenever a producer sorts after its
    // consumer (e.g. poseidon_aggregator after poseidon_3_partial_rounds_chain).
    let ordered = crate::arena_plan::topological_component_order(proof_plan)
        .map_err(|_| RecordedWitnessPlanError::UnorderableSchedule)?;
    let mut expected = Vec::new();
    for component in ordered {
        if component.node.facts.witness_writer.kind != WitnessWriterKind::RecordedAot
            || !component.runtime.is_present()
        {
            continue;
        }
        let RowResolution::Resolved(parts) = &component.runtime.rows else {
            return Err(RecordedWitnessPlanError::ShapeNotExact(component.node.id));
        };
        if parts.len() != 1 || parts[0].part != TracePartId::Main {
            return Err(RecordedWitnessPlanError::InvalidTracePart(
                component.node.id,
            ));
        }
        expected.push(ExpectedLane {
            node: component.node,
            n_real: usize::try_from(parts[0].n_real_rows)
                .map_err(|_| RecordedWitnessPlanError::SizeOverflow(component.node.id))?,
            row_count: usize::try_from(parts[0].padded_rows)
                .map_err(|_| RecordedWitnessPlanError::SizeOverflow(component.node.id))?,
        });
    }

    let labels = expected.iter().map(|lane| lane.node.id).collect::<Vec<_>>();
    let memory = generator
        .jit_memory
        .clone()
        .ok_or_else(|| RecordedWitnessInputsError::MissingExecutionMemory(labels.clone()))?;
    let execution_memory_identity = ExecutionMemoryIdentity::of(&memory);

    let mut attempts = Vec::with_capacity(expected.len());
    let mut unsupported = Vec::new();
    for lane in &expected {
        match recorded_witness_input_attempt(generator, lane.node.id)? {
            Some(attempt) => attempts.push(attempt),
            None => unsupported.push(lane.node.id),
        }
    }
    if !unsupported.is_empty() {
        return Err(RecordedWitnessPlanError::UnsupportedLabels(unsupported));
    }

    let mut lanes = Vec::with_capacity(expected.len());
    for (expected, attempt) in expected.into_iter().zip(attempts) {
        let program = attempt.program;
        let (columns, host_build_error) = match attempt.input_source {
            RecordedWitnessInputSource::Host(Ok(inputs)) => {
                let actual_padded = inputs.row_count();
                if inputs.n_real != expected.n_real || actual_padded != expected.row_count {
                    return Err(RecordedWitnessPlanError::RowGeometryMismatch {
                        component: expected.node.id,
                        expected_real: expected.n_real,
                        actual_real: inputs.n_real,
                        expected_padded: expected.row_count,
                        actual_padded,
                    });
                }
                (
                    inputs
                        .columns
                        .into_iter()
                        .map(RecordedInputColumnProvenance::Host)
                        .collect(),
                    None,
                )
            }
            RecordedWitnessInputSource::Host(Err(
                error @ RecordedInputBuildError::EmptyInputs(_),
            ))
            | RecordedWitnessInputSource::Host(Err(
                error @ RecordedInputBuildError::ScalarRemainder(_),
            ))
            | RecordedWitnessInputSource::Host(Err(
                error @ RecordedInputBuildError::DeviceSeedOnly(_),
            )) => (
                provenance_for_unmaterialized(
                    expected.node,
                    program.n_inputs as usize,
                    expected.n_real,
                    expected.row_count,
                    |producer| {
                        proof_plan.components.iter().any(|component| {
                            component.node.id == producer && component.runtime.is_present()
                        })
                    },
                )?,
                Some(error),
            ),
            RecordedWitnessInputSource::Host(Err(source)) => {
                return Err(RecordedWitnessPlanError::InputBuild {
                    component: expected.node.id,
                    source,
                });
            }
            RecordedWitnessInputSource::DeviceSeed(seed) => {
                if seed.n_real != expected.n_real || seed.row_count != expected.row_count {
                    return Err(RecordedWitnessPlanError::RowGeometryMismatch {
                        component: expected.node.id,
                        expected_real: expected.n_real,
                        actual_real: seed.n_real,
                        expected_padded: expected.row_count,
                        actual_padded: seed.row_count,
                    });
                }
                (
                    provenance_for_device_seed(
                        expected.node.id,
                        program.n_inputs as usize,
                        &seed.scalar_values,
                    )?,
                    None,
                )
            }
        };
        debug_assert_eq!(columns.len(), program.n_inputs as usize);
        lanes.push(PlannedRecordedWitnessInput {
            component: expected.node.id,
            program,
            row_count: expected.row_count,
            n_real: expected.n_real,
            columns,
            tables: RecordedTableIdentity {
                execution_memory: execution_memory_identity,
                host_pedersen_points_18: attempt.host_pedersen_points_18,
            },
            host_build_error,
        });
    }

    Ok(PlannedRecordedWitnessInputs {
        execution_memory: memory,
        execution_memory_identity,
        lanes,
    })
}

fn provenance_for_device_seed(
    component: ComponentId,
    n_inputs: usize,
    scalar_values: &[u32],
) -> Result<Vec<RecordedInputColumnProvenance>, RecordedWitnessPlanError> {
    let geometry = recorded_input_geometry(component)
        .ok_or(RecordedWitnessPlanError::MissingInputGeometry(component))?;
    let expected = scalar_values
        .len()
        .checked_add(usize::from(geometry.enabler_slot.is_some()))
        .and_then(|count| count.checked_add(usize::from(geometry.iota_slot.is_some())))
        .ok_or(RecordedWitnessPlanError::SizeOverflow(component))?;
    if n_inputs != expected
        || geometry.enabler_slot != Some(scalar_values.len())
        || geometry.iota_slot != Some(scalar_values.len() + 1)
    {
        return Err(RecordedWitnessPlanError::MissingInputGeometry(component));
    }
    let mut columns = scalar_values
        .iter()
        .copied()
        .enumerate()
        .map(|(index, value)| {
            RecordedInputColumnProvenance::DeviceSeed(DeviceSeedColumn::Scalar { index, value })
        })
        .collect::<Vec<_>>();
    columns.push(RecordedInputColumnProvenance::DeviceSeed(
        DeviceSeedColumn::Enabler,
    ));
    columns.push(RecordedInputColumnProvenance::DeviceSeed(
        DeviceSeedColumn::Iota,
    ));
    Ok(columns)
}

fn provenance_for_unmaterialized(
    node: &'static ComponentNode,
    n_inputs: usize,
    n_real: usize,
    row_count: usize,
    producer_is_active: impl Fn(ComponentId) -> bool,
) -> Result<Vec<RecordedInputColumnProvenance>, RecordedWitnessPlanError> {
    let geometry = recorded_input_geometry(node.id)
        .ok_or(RecordedWitnessPlanError::MissingInputGeometry(node.id))?;
    if node.id == "partial_ec_mul_generic" && producer_is_active("ec_op_builtin") {
        let ec_rows = n_real
            .checked_div(252)
            .filter(|_| n_real % 252 == 0)
            .ok_or(RecordedWitnessPlanError::MissingInputGeometry(node.id))?;
        // The recording treats iota as computed in-kernel (the lane convention),
        // so its inputs are the 125 data columns plus the enabler at slot 125.
        // The native ec_op writer still materializes the one-past-end iota
        // column into its own arena slot; the witness launch never binds it.
        if n_inputs != 126
            || geometry.enabler_slot != Some(125)
            || geometry.iota_slot != Some(126)
            || row_count != ec_rows.saturating_mul(256)
        {
            return Err(RecordedWitnessPlanError::MissingInputGeometry(node.id));
        }
        return Ok((0..n_inputs)
            .map(|ordinal| {
                RecordedInputColumnProvenance::DeviceNative(DeviceNativeColumn {
                    producer: "ec_op_builtin",
                    ordinal,
                })
            })
            .collect());
    }
    let producer_edges = node
        .inputs
        .iter()
        .filter_map(|edge| match edge {
            InputEdge::Producer {
                of,
                word_base,
                words_per_instance,
                n_instances,
            } if producer_is_active(*of) => {
                Some((*of, *word_base, *words_per_instance, *n_instances))
            }
            InputEdge::ExecTables | InputEdge::DeviceTable(_) => None,
            InputEdge::Producer { .. } => None,
        })
        .collect::<Vec<_>>();
    if let Some(compaction) = recorded_input_compaction_geometry(node.id) {
        let enabler_slot = geometry.enabler_slot;
        let iota_slot = geometry.iota_slot;
        if producer_edges.is_empty()
            || compaction.tuple_words == 0
            || compaction.tuple_words > n_inputs
            || compaction.multiplicity_slot >= n_inputs
            || enabler_slot.is_none_or(|slot| slot >= n_inputs)
            || iota_slot.is_none_or(|slot| slot >= n_inputs)
            || producer_edges
                .iter()
                .any(|edge| edge.2 as usize != compaction.tuple_words)
        {
            return Err(RecordedWitnessPlanError::MissingInputGeometry(node.id));
        }
        let mut columns = vec![None; n_inputs];
        for (word, destination) in columns[..compaction.tuple_words].iter_mut().enumerate() {
            *destination = Some(RecordedInputColumnProvenance::DeviceCompact(
                DeviceCompactColumn::Tuple { word },
            ));
        }
        columns[enabler_slot.unwrap()] = Some(RecordedInputColumnProvenance::DeviceCompact(
            DeviceCompactColumn::Enabler,
        ));
        columns[iota_slot.unwrap()] = Some(RecordedInputColumnProvenance::DeviceCompact(
            DeviceCompactColumn::Iota,
        ));
        columns[compaction.multiplicity_slot] = Some(RecordedInputColumnProvenance::DeviceCompact(
            DeviceCompactColumn::Multiplicity,
        ));
        return columns
            .into_iter()
            .collect::<Option<Vec<_>>>()
            .ok_or(RecordedWitnessPlanError::MissingInputGeometry(node.id));
    }
    let data_ordinals = (0..n_inputs)
        .filter(|ordinal| {
            Some(*ordinal) != geometry.enabler_slot && Some(*ordinal) != geometry.iota_slot
        })
        .collect::<Vec<_>>();
    let unresolved_reason = match producer_edges.as_slice() {
        [] => UnresolvedColumnReason::NoProducerEdge,
        [_] => UnresolvedColumnReason::ProducerEdgeGeometryMismatch {
            producer_words: producer_edges[0].2 as usize,
            consumer_data_columns: data_ordinals.len(),
        },
        edges => UnresolvedColumnReason::ProducerEdgesRequireCompaction {
            producer_count: edges.len(),
        },
    };
    let mut columns = (0..n_inputs)
        .map(|ordinal| {
            RecordedInputColumnProvenance::Unresolved(UnresolvedInputColumn {
                component: node.id,
                ordinal,
                reason: unresolved_reason.clone(),
            })
        })
        .collect::<Vec<_>>();

    let multi_gather = producer_edges.len() > 1
        && producer_edges
            .iter()
            .all(|edge| edge.2 as usize == data_ordinals.len());
    if let [(producer, word_base, words_per_instance, n_instances)] = producer_edges.as_slice() {
        if *words_per_instance as usize == data_ordinals.len() {
            for (source_offset, &ordinal) in data_ordinals.iter().enumerate() {
                columns[ordinal] = RecordedInputColumnProvenance::DeviceEdge(DeviceEdgeColumn {
                    producer: *producer,
                    source_kind: DeviceEdgeSourceKind::SubcomponentWords,
                    source_word: *word_base + source_offset as u32,
                    words_per_instance: *words_per_instance,
                    n_instances: *n_instances,
                });
            }
        }
    } else if multi_gather {
        for (source_offset, &ordinal) in data_ordinals.iter().enumerate() {
            columns[ordinal] =
                RecordedInputColumnProvenance::DeviceGather(DeviceGatherColumn::Data {
                    edges: producer_edges
                        .iter()
                        .map(|(producer, word_base, words_per_instance, n_instances)| {
                            DeviceEdgeColumn {
                                producer: *producer,
                                source_kind: DeviceEdgeSourceKind::SubcomponentWords,
                                source_word: *word_base + source_offset as u32,
                                words_per_instance: *words_per_instance,
                                n_instances: *n_instances,
                            }
                        })
                        .collect(),
                });
        }
    }
    if let Some(ordinal) = geometry.enabler_slot.filter(|&ordinal| ordinal < n_inputs) {
        columns[ordinal] = if multi_gather {
            RecordedInputColumnProvenance::DeviceGather(DeviceGatherColumn::Enabler)
        } else {
            RecordedInputColumnProvenance::Host(
                (0..row_count).map(|row| u32::from(row < n_real)).collect(),
            )
        };
    }
    if let Some(ordinal) = geometry.iota_slot.filter(|&ordinal| ordinal < n_inputs) {
        columns[ordinal] = if multi_gather {
            RecordedInputColumnProvenance::DeviceGather(DeviceGatherColumn::Iota)
        } else {
            RecordedInputColumnProvenance::Host(
                (0..row_count)
                    .map(|row| u32::try_from(row).expect("Cairo trace row exceeds u32"))
                    .collect(),
            )
        };
    }
    Ok(columns)
}

#[cfg(test)]
mod tests {
    use stwo_cairo_adapter::memory::{EncodedMemoryValueId, MemoryConfig};
    use stwo_cairo_common::prover_types::cpu::{CasmState, M31};
    use stwo_cairo_prover::witness::components::{
        poseidon_3_partial_rounds_chain, poseidon_aggregator, poseidon_builtin,
        poseidon_full_round_chain,
    };
    use stwo_cairo_prover::witness::jit_prove_backend::all_lane_recordings;

    use super::*;
    use crate::plan::ProofPlan;
    use crate::relation_table::CAIRO_RELATION_GRAPH;
    use crate::schedule_table::CAIRO_SCHEDULE;

    fn node(id: ComponentId) -> &'static ComponentNode {
        CAIRO_SCHEDULE
            .nodes
            .iter()
            .find(|node| node.id == id)
            .unwrap()
    }

    fn n_inputs(label: &str) -> usize {
        all_lane_recordings()
            .into_iter()
            .find(|(recorded, _)| *recorded == label)
            .unwrap()
            .1
            .n_inputs as usize
    }

    #[test]
    fn direct_w18_edge_and_host_enabler_have_exact_column_provenance() {
        let component = node("partial_ec_mul_window_bits_18");
        let columns =
            provenance_for_unmaterialized(component, n_inputs(component.id), 56, 64, |_| true)
                .unwrap();
        assert_eq!(columns.len(), 73);
        for (ordinal, source) in columns[..72].iter().enumerate() {
            assert!(matches!(
                source,
                RecordedInputColumnProvenance::DeviceEdge(DeviceEdgeColumn {
                    producer: "pedersen_aggregator_window_bits_18",
                    source_word,
                    words_per_instance: 72,
                    n_instances: 28,
                    ..
                }) if *source_word == 7 + ordinal as u32
            ));
        }
        assert!(matches!(
            columns[72],
            RecordedInputColumnProvenance::Host(_)
        ));
        assert!(columns
            .iter()
            .all(|source| !matches!(source, RecordedInputColumnProvenance::Unresolved(_))));
        let RecordedInputColumnProvenance::Host(enabler) = &columns[72] else {
            unreachable!()
        };
        assert_eq!(enabler.len(), 64);
        assert!(enabler[..56].iter().all(|&value| value == 1));
        assert!(enabler[56..].iter().all(|&value| value == 0));
        // This recording never reads iota, so the normalized recorder ABI
        // deliberately truncates the generated writer's trailing iota column.
    }

    #[test]
    fn poseidon_vec_consumers_use_ordered_multi_edge_gathers_without_host_columns() {
        for (component, expected) in [
            (
                "cube_252",
                vec![
                    ("poseidon_aggregator", 282, 2),
                    ("poseidon_3_partial_rounds_chain", 1, 3),
                    ("poseidon_full_round_chain", 0, 3),
                ],
            ),
            (
                "range_check_252_width_27",
                vec![
                    ("poseidon_aggregator", 262, 2),
                    ("poseidon_3_partial_rounds_chain", 61, 3),
                ],
            ),
        ] {
            let columns = provenance_for_unmaterialized(
                node(component),
                n_inputs(component),
                80,
                128,
                |_| true,
            )
            .unwrap();
            assert_eq!(columns.len(), 11, "{component}");
            for (word, source) in columns[..10].iter().enumerate() {
                let RecordedInputColumnProvenance::DeviceGather(DeviceGatherColumn::Data { edges }) =
                    source
                else {
                    panic!("{component} input {word} is not a device gather: {source:?}")
                };
                assert_eq!(edges.len(), expected.len(), "{component} input {word}");
                for (edge, &(producer, word_base, n_instances)) in edges.iter().zip(&expected) {
                    assert_eq!(
                        edge,
                        &DeviceEdgeColumn {
                            producer,
                            source_kind: DeviceEdgeSourceKind::SubcomponentWords,
                            source_word: word_base + word as u32,
                            words_per_instance: 10,
                            n_instances,
                        },
                        "{component} input {word} producer order",
                    );
                }
            }
            assert_eq!(
                columns[10],
                RecordedInputColumnProvenance::DeviceGather(DeviceGatherColumn::Enabler),
                "{component}",
            );
            // The generated row bodies never read iota, so recording
            // normalization removes slot 11 from both live programs.
            assert!(columns.iter().all(|source| !matches!(
                source,
                RecordedInputColumnProvenance::Host(_)
                    | RecordedInputColumnProvenance::Unresolved(_)
            )));
        }
    }

    #[test]
    fn multiset_consumer_edges_are_device_compacted() {
        let component = node("verify_instruction");
        let columns =
            provenance_for_unmaterialized(component, n_inputs(component.id), 16, 16, |_| true)
                .unwrap();
        assert_eq!(columns.len(), 10);
        for (word, column) in columns[..7].iter().enumerate() {
            assert_eq!(
                column,
                &RecordedInputColumnProvenance::DeviceCompact(DeviceCompactColumn::Tuple { word })
            );
        }
        assert_eq!(
            columns[7],
            RecordedInputColumnProvenance::DeviceCompact(DeviceCompactColumn::Enabler)
        );
        assert_eq!(
            columns[8],
            RecordedInputColumnProvenance::DeviceCompact(DeviceCompactColumn::Iota)
        );
        assert_eq!(
            columns[9],
            RecordedInputColumnProvenance::DeviceCompact(DeviceCompactColumn::Multiplicity)
        );
    }

    #[test]
    fn ec_op_writes_all_partial_generic_columns_directly() {
        let component = node("partial_ec_mul_generic");
        let columns = provenance_for_unmaterialized(
            component,
            n_inputs(component.id),
            16 * 252,
            16 * 256,
            |producer| producer == "ec_op_builtin",
        )
        .unwrap();
        // 125 data columns plus the enabler at slot 125; iota is computed
        // in-kernel and is not a bound input (see recorded_input_geometry's
        // one-past-end iota convention shared with the w18 lane).
        assert_eq!(columns.len(), 126);
        for (ordinal, source) in columns.iter().enumerate() {
            assert_eq!(
                source,
                &RecordedInputColumnProvenance::DeviceNative(DeviceNativeColumn {
                    producer: "ec_op_builtin",
                    ordinal,
                })
            );
        }
    }

    #[test]
    fn poseidon_aggregator_uses_the_exact_device_compact_writer_abi() {
        let component = node("poseidon_aggregator");
        let columns =
            provenance_for_unmaterialized(component, n_inputs(component.id), 16, 16, |producer| {
                producer == "poseidon_builtin"
            })
            .unwrap();
        assert_eq!(columns.len(), 9);
        for (word, column) in columns[..6].iter().enumerate() {
            assert_eq!(
                column,
                &RecordedInputColumnProvenance::DeviceCompact(DeviceCompactColumn::Tuple { word })
            );
        }
        assert_eq!(
            columns[6],
            RecordedInputColumnProvenance::DeviceCompact(DeviceCompactColumn::Enabler)
        );
        assert_eq!(
            columns[7],
            RecordedInputColumnProvenance::DeviceCompact(DeviceCompactColumn::Iota)
        );
        assert_eq!(
            columns[8],
            RecordedInputColumnProvenance::DeviceCompact(DeviceCompactColumn::Multiplicity)
        );
    }

    #[test]
    fn poseidon_device_only_chain_resolves_to_arena_input_materializers() {
        let memory = Arc::new(Memory {
            config: MemoryConfig::default(),
            address_to_id: vec![EncodedMemoryValueId(0)],
            f252_values: vec![[0; 8]],
            small_values: vec![0],
        });
        let generator = CairoClaimGenerator {
            jit_memory: Some(memory),
            poseidon_builtin: Some(poseidon_builtin::ClaimGenerator::new(4, 17)),
            poseidon_aggregator: Some(poseidon_aggregator::ClaimGenerator::new()),
            poseidon_full_round_chain: Some(poseidon_full_round_chain::ClaimGenerator::new()),
            poseidon_3_partial_rounds_chain: Some(
                poseidon_3_partial_rounds_chain::ClaimGenerator::new(),
            ),
            ..CairoClaimGenerator::default()
        };
        let capacity = ProofPlan::from_schedule(
            &CAIRO_SCHEDULE,
            &CAIRO_RELATION_GRAPH,
            &generator.proof_shape(None).unwrap(),
        )
        .unwrap();
        // The strict resolution fails closed on the compacted aggregator's
        // capacity bound; this lane-provenance test substitutes the capacity
        // geometry explicitly (see resolve_compacted_capacity_for_test).
        let exact = crate::plan::resolve_compacted_capacity_for_test(
            &capacity,
            &CAIRO_SCHEDULE,
            &CAIRO_RELATION_GRAPH,
        )
        .strict_resident_exact(&CAIRO_SCHEDULE, &CAIRO_RELATION_GRAPH)
        .unwrap();
        let planned = recorded_witness_inputs_for_plan(&generator, &exact).unwrap();
        planned.require_resolved().unwrap();
        assert_eq!(planned.lanes.len(), 4);

        let lane = |component| {
            planned
                .lanes
                .iter()
                .find(|lane| lane.component == component)
                .unwrap()
        };
        assert_eq!(
            lane("poseidon_builtin").columns,
            [
                RecordedInputColumnProvenance::DeviceSeed(DeviceSeedColumn::Scalar {
                    index: 0,
                    value: 17,
                }),
                RecordedInputColumnProvenance::DeviceSeed(DeviceSeedColumn::Enabler),
                RecordedInputColumnProvenance::DeviceSeed(DeviceSeedColumn::Iota),
            ]
        );
        assert!(lane("poseidon_aggregator")
            .columns
            .iter()
            .all(|source| matches!(source, RecordedInputColumnProvenance::DeviceCompact(_))));

        for (component, word_base, input_width, n_instances) in [
            ("poseidon_full_round_chain", 6, 32, 8),
            ("poseidon_3_partial_rounds_chain", 342, 42, 27),
        ] {
            let lane = lane(component);
            // These generated chain writers read the producer words and the
            // enabler, but not iota; input normalization removes that trailing
            // unused column from the recorded ABI.
            assert_eq!(lane.columns.len(), input_width + 1);
            for (ordinal, source) in lane.columns[..input_width].iter().enumerate() {
                assert!(matches!(
                    source,
                    RecordedInputColumnProvenance::DeviceEdge(DeviceEdgeColumn {
                        producer: "poseidon_aggregator",
                        source_word,
                        words_per_instance,
                        n_instances: actual_instances,
                        ..
                    }) if *source_word == word_base + ordinal as u32
                        && *words_per_instance == input_width as u32
                        && *actual_instances == n_instances
                ));
            }
            assert!(matches!(
                lane.columns[input_width],
                RecordedInputColumnProvenance::Host(_)
            ));
        }
    }

    #[test]
    fn exact_host_lane_covers_program_rows_and_retains_memory_identity() {
        let memory = Arc::new(Memory {
            config: MemoryConfig::default(),
            address_to_id: vec![EncodedMemoryValueId(0)],
            f252_values: vec![[0; 8]],
            small_values: vec![0],
        });
        let mut generator = CairoClaimGenerator {
            jit_memory: Some(memory.clone()),
            ..CairoClaimGenerator::default()
        };
        generator.add_opcode = Some(
            stwo_cairo_prover::witness::components::add_opcode::ClaimGenerator::new(vec![
                CasmState {
                    pc: M31::from_u32_unchecked(1),
                    ap: M31::from_u32_unchecked(2),
                    fp: M31::from_u32_unchecked(3),
                },
                CasmState {
                    pc: M31::from_u32_unchecked(4),
                    ap: M31::from_u32_unchecked(5),
                    fp: M31::from_u32_unchecked(6),
                },
                CasmState {
                    pc: M31::from_u32_unchecked(7),
                    ap: M31::from_u32_unchecked(8),
                    fp: M31::from_u32_unchecked(9),
                },
            ]),
        );
        let shape = generator.proof_shape(None).unwrap();
        let plan =
            ProofPlan::from_schedule(&CAIRO_SCHEDULE, &CAIRO_RELATION_GRAPH, &shape).unwrap();
        let planned = recorded_witness_inputs_for_plan(&generator, &plan).unwrap();

        assert!(Arc::ptr_eq(&planned.execution_memory, &memory));
        assert_eq!(
            planned.execution_memory_identity,
            ExecutionMemoryIdentity::of(&memory)
        );
        assert_eq!(planned.lanes.len(), 1);
        let lane = &planned.lanes[0];
        assert_eq!(lane.component, "add_opcode");
        assert_eq!(lane.program.label, lane.component);
        assert_eq!(lane.n_real, 3);
        assert_eq!(lane.row_count, 16);
        assert_eq!(lane.columns.len(), lane.program.n_inputs as usize);
        assert!(lane
            .columns
            .iter()
            .all(|source| matches!(source, RecordedInputColumnProvenance::Host(column) if column.len() == lane.row_count)));
        assert!(planned.unresolved_columns().is_empty());
        planned.require_resolved().unwrap();
        let RecordedInputColumnProvenance::Host(pc) = &lane.columns[0] else {
            unreachable!()
        };
        assert_eq!(&pc[..3], &[1, 4, 7]);
    }
}
