//! The component schedule as data (design §3.3, §16.3).
//!
//! The Cairo component DAG — today implicit in `cairo_claim_generator` spawn order
//! plus the stash/edge seams — becomes an explicit table the scheduler consumes:
//! topological levels → stream assignment → event edges → the witness graph's
//! capture order. M1 lands the TYPES and [`Schedule::validate`]; the table itself
//! is GENERATED by `tools/schedule_emit` at M2 (design R8: the table is derivable
//! metadata, hand-writing it is the data-entry class of bug the transformer work
//! already eliminated twice).

use stwo_cairo_prover::witness::exec_context::{PlannedDeviceEdge, WitnessArtifactPlan};

/// Stable component identity: the component's module name as the transformer and
/// the phase ledger already use it (e.g. `"add_opcode"`, `"partial_ec_mul_window_bits_18"`).
pub type ComponentId = &'static str;

/// AOT kernel manifest key: (semantic hash, codegen version) — matches the cache
/// keys the witness/constraint lanes already compute. Until M3 (AOT registry) the
/// key is informational.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct KernelKey {
    pub semantic_hash: u64,
    pub codegen_version: u64,
}

/// Where a component's row count comes from.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LogSizeSource {
    /// From the adapter's packed states for this opcode/builtin.
    FromStates,
    /// Derived from a producer's instance count (e.g. w18 rows = 28 × aggregator rows).
    FromProducer(ComponentId),
    /// Fixed by the AIR (preprocessed-table components).
    Fixed(u32),
}

/// One input edge of a component.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum InputEdge {
    /// Consume a word range of `of`'s sub-input buffer (device edge; the
    /// gather-kernel pattern proven for aggregator→w18 and blake_round→blake_g).
    /// `n_instances` feed instances of `words_per_instance` words each, starting
    /// at `word_base` (e.g. aggregator→w18: 28 × 72 words @ base 7).
    Producer {
        of: ComponentId,
        word_base: u32,
        words_per_instance: u32,
        n_instances: u32,
    },
    /// Reads via the device execution tables (opcode family).
    ExecTables,
    /// Reads a resident device table (pedersen points, sigma LUTs, …).
    DeviceTable(&'static str),
}

/// One output edge: a word range of this component's sub buffer consumed downstream.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct OutputEdge {
    pub to: ComponentId,
    pub word_base: u32,
    pub words_per_instance: u32,
    pub n_instances: u32,
}

/// A count-relation feed (device-atomic family), matching the emitted
/// `SUB_FEED_LAYOUT` + the `COUNT_RELATIONS` registry.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct CountFeed {
    pub family: &'static str,
    pub n_relations: u32,
}

/// A generated row-capacity contribution. Each producer row contributes
/// `n_instances` packed relation inputs to the consumer. Unlike [`OutputEdge`],
/// this fact does not claim that a device word-range transport exists; it is
/// available for every generated `SubComponentInputs` field.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct CapacityFeed {
    pub from: ComponentId,
    pub n_instances: u32,
}

/// The pinned input-column slot layout `[flat 0..K | enabler | iota | mults..]`
/// the builtin lane validates before launch.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SlotLayout {
    pub n_flat: u32,
    pub has_enabler: bool,
    pub has_iota: bool,
    pub n_mults: u32,
}

/// Base-trace width emitted from cairo-air. `memory_id_to_big` is the sole
/// aggregate generator that expands to a variable number of big-memory traces
/// plus one small-memory trace, so its two AIR widths remain explicit.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TraceColumnCount {
    Fixed(u32),
    SplitMemory { big: u32, small: u32 },
}

/// Mechanically established source of a component's runtime row geometry.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ComponentRowSource {
    /// Final adapter-provided `inputs.len()`; padded to a SIMD power of two.
    DirectInputs,
    /// A generator-owned `log_size` field.
    StoredLogSize,
    /// AIR-fixed table size.
    FixedLogSize(u32),
    /// Inputs or unique multiplicity keys are still added by upstream witness
    /// writers. The pre-witness shape must remain explicitly unresolved.
    WitnessRelationFeeds,
    /// Split memory-address table formula.
    MemoryAddress,
    /// Variable big-memory components plus the small-memory component.
    MemoryIdToBig,
}

/// A semantic witness recording exists and can produce the eventual AOT key.
/// The key itself is not emitted by `schedule_emit`: it belongs to kernel_emit's
/// recording/compiler manifest and must not be guessed from source labels.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum KernelIdentitySource {
    None,
    RecordedWitness,
}

/// Concrete implementation used to materialize one component's base witness.
/// This is deliberately separate from [`KernelIdentitySource`]: a semantic
/// recording can exist while its live writer still allocates temporary buffers
/// and is therefore not admissible to a captured resident proof.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum WitnessWriterKind {
    Host,
    RecordedAot,
    NativeCuda,
    FixedTableCuda,
}

/// How far the live writer has progressed toward the strict Graph-A contract.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum WitnessWriterReadiness {
    Detached,
    ArenaDestination,
    CaptureSafe,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct WitnessWriterSpec {
    pub kind: WitnessWriterKind,
    pub readiness: WitnessWriterReadiness,
}

impl WitnessWriterSpec {
    pub const HOST: Self = Self {
        kind: WitnessWriterKind::Host,
        readiness: WitnessWriterReadiness::Detached,
    };

    pub const fn uses_arena_destination(self) -> bool {
        !matches!(self.readiness, WitnessWriterReadiness::Detached)
    }

    pub const fn is_capture_safe(self) -> bool {
        matches!(self.readiness, WitnessWriterReadiness::CaptureSafe)
    }
}

/// Static component facts derived from generated witness and cairo-air sources.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ComponentStaticFacts {
    pub trace_columns: TraceColumnCount,
    pub lookup_words: Option<u32>,
    pub sub_words: Option<u32>,
    pub logup_columns: Option<u32>,
    pub row_source: ComponentRowSource,
    pub kernel_identity: KernelIdentitySource,
    pub witness_writer: WitnessWriterSpec,
}

/// One row of the schedule table (design §16.3).
#[derive(Clone, Copy, Debug)]
pub struct ComponentNode {
    pub id: ComponentId,
    pub facts: ComponentStaticFacts,
    pub kernel: Option<KernelKey>,
    pub log_size: LogSizeSource,
    pub inputs: &'static [InputEdge],
    pub capacity_inputs: &'static [CapacityFeed],
    pub outputs: &'static [OutputEdge],
    pub counts: &'static [CountFeed],
    pub slots: Option<SlotLayout>,
}

#[derive(Debug, PartialEq, Eq)]
pub enum ScheduleError {
    DuplicateComponent(ComponentId),
    /// An edge references a component that has no node.
    DanglingEdge {
        from: ComponentId,
        to: ComponentId,
    },
    /// Producer/consumer word ranges disagree.
    EdgeWidthMismatch {
        producer: ComponentId,
        consumer: ComponentId,
    },
    /// The dependency graph has a cycle (component reachable from itself).
    Cycle(ComponentId),
}

impl std::fmt::Display for ScheduleError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{self:?}")
    }
}

impl std::error::Error for ScheduleError {}

pub struct Schedule {
    pub nodes: &'static [ComponentNode],
}

impl Schedule {
    /// The schedule facts consumed by live per-proof witness artifact transport.
    /// This is the first production consumer of the generated table: device lookup
    /// labels and producer-edge geometry fail closed against these facts.
    pub fn artifact_plan(&self) -> Result<WitnessArtifactPlan, ScheduleError> {
        self.validate()?;
        let components = self.nodes.iter().map(|node| node.id).collect();
        let edges = self
            .nodes
            .iter()
            .flat_map(|consumer| {
                consumer.inputs.iter().filter_map(|input| match input {
                    InputEdge::Producer {
                        of,
                        word_base,
                        words_per_instance,
                        n_instances,
                    } => Some(PlannedDeviceEdge {
                        producer: *of,
                        consumer: consumer.id,
                        word_base: *word_base,
                        words_per_instance: *words_per_instance,
                        n_instances: *n_instances,
                    }),
                    InputEdge::ExecTables | InputEdge::DeviceTable(_) => None,
                })
            })
            .collect();
        Ok(WitnessArtifactPlan::new(components, edges))
    }

    /// Topological levels: nodes whose producer edges are all satisfied by earlier
    /// levels. Level order is the stream plan and (at M5) the graph capture order.
    pub fn levels(&self) -> Result<Vec<Vec<ComponentId>>, ScheduleError> {
        self.validate()?;
        let mut placed: Vec<ComponentId> = Vec::new();
        let mut levels: Vec<Vec<ComponentId>> = Vec::new();
        while placed.len() < self.nodes.len() {
            let level: Vec<ComponentId> = self
                .nodes
                .iter()
                .filter(|n| !placed.contains(&n.id))
                .filter(|n| {
                    n.inputs.iter().all(|e| match e {
                        InputEdge::Producer { of, .. } => placed.contains(of),
                        _ => true,
                    }) && n
                        .capacity_inputs
                        .iter()
                        .all(|feed| placed.contains(&feed.from))
                })
                .map(|n| n.id)
                .collect();
            if level.is_empty() {
                // validate() rejects cycles, so this is unreachable; keep it as a
                // defensive error rather than an infinite loop.
                return Err(ScheduleError::Cycle(
                    self.nodes
                        .iter()
                        .find(|n| !placed.contains(&n.id))
                        .map(|n| n.id)
                        .unwrap_or("<none>"),
                ));
            }
            placed.extend(&level);
            levels.push(level);
        }
        Ok(levels)
    }

    /// Structural validation (runs in CI once the table is emitted): unique ids,
    /// no dangling edges, producer/consumer width agreement, acyclicity.
    pub fn validate(&self) -> Result<(), ScheduleError> {
        // Unique ids.
        for (i, n) in self.nodes.iter().enumerate() {
            if self.nodes[..i].iter().any(|m| m.id == n.id) {
                return Err(ScheduleError::DuplicateComponent(n.id));
            }
        }
        let find = |id: ComponentId| self.nodes.iter().find(|n| n.id == id);
        // Dangling edges + width agreement (each consumer Producer edge must have a
        // matching OutputEdge on the producer).
        for n in self.nodes {
            for feed in n.capacity_inputs {
                if find(feed.from).is_none() {
                    return Err(ScheduleError::DanglingEdge {
                        from: feed.from,
                        to: n.id,
                    });
                }
            }
            for e in n.inputs {
                if let InputEdge::Producer {
                    of,
                    word_base,
                    words_per_instance,
                    n_instances,
                } = e
                {
                    let Some(producer) = find(of) else {
                        return Err(ScheduleError::DanglingEdge {
                            from: *of,
                            to: n.id,
                        });
                    };
                    let matched = producer.outputs.iter().any(|o| {
                        o.to == n.id
                            && o.word_base == *word_base
                            && o.words_per_instance == *words_per_instance
                            && o.n_instances == *n_instances
                    });
                    if !matched {
                        return Err(ScheduleError::EdgeWidthMismatch {
                            producer: *of,
                            consumer: n.id,
                        });
                    }
                }
            }
            for o in n.outputs {
                if find(o.to).is_none() {
                    return Err(ScheduleError::DanglingEdge {
                        from: n.id,
                        to: o.to,
                    });
                }
            }
        }
        // Acyclicity via DFS.
        fn dfs(
            nodes: &[ComponentNode],
            id: ComponentId,
            visiting: &mut Vec<ComponentId>,
            done: &mut Vec<ComponentId>,
        ) -> Result<(), ScheduleError> {
            if done.contains(&id) {
                return Ok(());
            }
            if visiting.contains(&id) {
                return Err(ScheduleError::Cycle(id));
            }
            visiting.push(id);
            let node = nodes.iter().find(|n| n.id == id).expect("checked above");
            for e in node.inputs {
                if let InputEdge::Producer { of, .. } = e {
                    dfs(nodes, of, visiting, done)?;
                }
            }
            for feed in node.capacity_inputs {
                dfs(nodes, feed.from, visiting, done)?;
            }
            visiting.retain(|v| *v != id);
            done.push(id);
            Ok(())
        }
        let mut done = Vec::new();
        for n in self.nodes {
            dfs(self.nodes, n.id, &mut Vec::new(), &mut done)?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // A hand miniature of the real shape: aggregator → w18 (28×72 words @ base 7),
    // used ONLY to pin validate()/levels() semantics. The production table is
    // emitted by schedule_emit (M2), never hand-written (R8).
    const AGG_OUT: &[OutputEdge] = &[OutputEdge {
        to: "partial_ec_mul_window_bits_18",
        word_base: 7,
        words_per_instance: 72,
        n_instances: 28,
    }];
    const W18_IN: &[InputEdge] = &[InputEdge::Producer {
        of: "pedersen_aggregator_window_bits_18",
        word_base: 7,
        words_per_instance: 72,
        n_instances: 28,
    }];
    const NODES: &[ComponentNode] = &[
        ComponentNode {
            id: "pedersen_aggregator_window_bits_18",
            facts: ComponentStaticFacts {
                trace_columns: TraceColumnCount::Fixed(206),
                lookup_words: Some(396),
                sub_words: Some(2023),
                logup_columns: Some(6),
                row_source: ComponentRowSource::WitnessRelationFeeds,
                kernel_identity: KernelIdentitySource::RecordedWitness,
                witness_writer: WitnessWriterSpec {
                    kind: WitnessWriterKind::RecordedAot,
                    readiness: WitnessWriterReadiness::ArenaDestination,
                },
            },
            kernel: None,
            log_size: LogSizeSource::FromStates,
            inputs: &[InputEdge::ExecTables],
            capacity_inputs: &[],
            outputs: AGG_OUT,
            counts: &[CountFeed {
                family: "rc_8",
                n_relations: 1,
            }],
            slots: Some(SlotLayout {
                n_flat: 5,
                has_enabler: true,
                has_iota: true,
                n_mults: 1,
            }),
        },
        ComponentNode {
            id: "partial_ec_mul_window_bits_18",
            facts: ComponentStaticFacts {
                trace_columns: TraceColumnCount::Fixed(297),
                lookup_words: Some(498),
                sub_words: Some(169),
                logup_columns: Some(65),
                row_source: ComponentRowSource::WitnessRelationFeeds,
                kernel_identity: KernelIdentitySource::RecordedWitness,
                witness_writer: WitnessWriterSpec {
                    kind: WitnessWriterKind::RecordedAot,
                    readiness: WitnessWriterReadiness::ArenaDestination,
                },
            },
            kernel: None,
            log_size: LogSizeSource::FromProducer("pedersen_aggregator_window_bits_18"),
            inputs: W18_IN,
            capacity_inputs: &[CapacityFeed {
                from: "pedersen_aggregator_window_bits_18",
                n_instances: 28,
            }],
            outputs: &[],
            counts: &[],
            slots: Some(SlotLayout {
                n_flat: 72,
                has_enabler: true,
                has_iota: true,
                n_mults: 0,
            }),
        },
    ];

    #[test]
    fn valid_two_node_schedule() {
        let s = Schedule { nodes: NODES };
        s.validate().unwrap();
        let levels = s.levels().unwrap();
        assert_eq!(levels.len(), 2);
        assert_eq!(levels[0], vec!["pedersen_aggregator_window_bits_18"]);
        assert_eq!(levels[1], vec!["partial_ec_mul_window_bits_18"]);
    }

    #[test]
    fn width_mismatch_rejected() {
        const BAD_IN: &[InputEdge] = &[InputEdge::Producer {
            of: "pedersen_aggregator_window_bits_18",
            word_base: 7,
            words_per_instance: 71, // wrong width
            n_instances: 28,
        }];
        let nodes: &'static [ComponentNode] = Box::leak(Box::new([
            NODES[0],
            ComponentNode {
                inputs: BAD_IN,
                ..NODES[1]
            },
        ]));
        let s = Schedule { nodes };
        assert!(matches!(
            s.validate(),
            Err(ScheduleError::EdgeWidthMismatch { .. })
        ));
    }

    #[test]
    fn dangling_edge_rejected() {
        let nodes: &'static [ComponentNode] = Box::leak(Box::new([NODES[1]]));
        let s = Schedule { nodes };
        assert!(matches!(
            s.validate(),
            Err(ScheduleError::DanglingEdge { .. })
        ));
    }
}
