//! MACHINE-WRITTEN by tools/schedule_emit — DO NOT EDIT (design R8/§17).
//! Regenerate: `cargo run --manifest-path tools/schedule_emit/Cargo.toml`;
//! CI drift gate: same command with `--check`.
//!
//! The Cairo component feed DAG, derived from the transformer-emitted
//! SUB_FEED_LAYOUT consts + the COUNT_RELATIONS registry. Node order is
//! alphabetical (stable emission); EXECUTION order comes from
//! `Schedule::levels()`; trace COLLECTION order stays the claim
//! generator's (Fiat-Shamir-fixed) and is not this table's concern.

use crate::schedule::{ComponentNode, CountFeed, InputEdge, LogSizeSource, OutputEdge, Schedule};

pub static CAIRO_SCHEDULE: Schedule = Schedule { nodes: NODES };

static NODES: &[ComponentNode] = &[
    ComponentNode {
        id: "add_ap_opcode",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[
            OutputEdge {
                to: "memory_address_to_id",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 1,
            },
            OutputEdge {
                to: "memory_id_to_big",
                word_base: 8,
                words_per_instance: 1,
                n_instances: 1,
            },
            OutputEdge {
                to: "verify_instruction",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
        ],
        counts: &[
            CountFeed {
                family: "range_check_11_state",
                n_relations: 1,
            },
            CountFeed {
                family: "range_check_18_state",
                n_relations: 1,
            },
        ],
        slots: None,
    },
    ComponentNode {
        id: "add_opcode",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[
            OutputEdge {
                to: "memory_address_to_id",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 3,
            },
            OutputEdge {
                to: "memory_id_to_big",
                word_base: 10,
                words_per_instance: 1,
                n_instances: 3,
            },
            OutputEdge {
                to: "verify_instruction",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
        ],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "add_opcode_small",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[
            OutputEdge {
                to: "memory_address_to_id",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 3,
            },
            OutputEdge {
                to: "memory_id_to_big",
                word_base: 10,
                words_per_instance: 1,
                n_instances: 3,
            },
            OutputEdge {
                to: "verify_instruction",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
        ],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "assert_eq_opcode",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[
            OutputEdge {
                to: "memory_address_to_id",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 2,
            },
            OutputEdge {
                to: "verify_instruction",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
        ],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "assert_eq_opcode_double_deref",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[
            OutputEdge {
                to: "memory_address_to_id",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 3,
            },
            OutputEdge {
                to: "memory_id_to_big",
                word_base: 10,
                words_per_instance: 1,
                n_instances: 1,
            },
            OutputEdge {
                to: "verify_instruction",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
        ],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "assert_eq_opcode_imm",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[
            OutputEdge {
                to: "memory_address_to_id",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 2,
            },
            OutputEdge {
                to: "verify_instruction",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
        ],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "blake_g",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[InputEdge::Producer {
            of: "blake_round",
            word_base: 81,
            words_per_instance: 6,
            n_instances: 8,
        }],
        outputs: &[
            OutputEdge {
                to: "verify_bitwise_xor_12",
                word_base: 24,
                words_per_instance: 3,
                n_instances: 2,
            },
            OutputEdge {
                to: "verify_bitwise_xor_4",
                word_base: 30,
                words_per_instance: 3,
                n_instances: 2,
            },
            OutputEdge {
                to: "verify_bitwise_xor_7",
                word_base: 36,
                words_per_instance: 3,
                n_instances: 2,
            },
            OutputEdge {
                to: "verify_bitwise_xor_8",
                word_base: 0,
                words_per_instance: 3,
                n_instances: 8,
            },
            OutputEdge {
                to: "verify_bitwise_xor_9",
                word_base: 42,
                words_per_instance: 3,
                n_instances: 2,
            },
        ],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "blake_round",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[
            OutputEdge {
                to: "blake_g",
                word_base: 81,
                words_per_instance: 6,
                n_instances: 8,
            },
            OutputEdge {
                to: "blake_round_sigma",
                word_base: 0,
                words_per_instance: 1,
                n_instances: 1,
            },
            OutputEdge {
                to: "memory_address_to_id",
                word_base: 49,
                words_per_instance: 1,
                n_instances: 16,
            },
            OutputEdge {
                to: "memory_id_to_big",
                word_base: 65,
                words_per_instance: 1,
                n_instances: 16,
            },
        ],
        counts: &[CountFeed {
            family: "range_check_7_2_5_state",
            n_relations: 1,
        }],
        slots: None,
    },
    ComponentNode {
        id: "blake_round_sigma",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[InputEdge::Producer {
            of: "blake_round",
            word_base: 0,
            words_per_instance: 1,
            n_instances: 1,
        }],
        outputs: &[],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "call_opcode_abs",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[
            OutputEdge {
                to: "memory_address_to_id",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 3,
            },
            OutputEdge {
                to: "memory_id_to_big",
                word_base: 10,
                words_per_instance: 1,
                n_instances: 3,
            },
            OutputEdge {
                to: "verify_instruction",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
        ],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "call_opcode_rel_imm",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[
            OutputEdge {
                to: "memory_address_to_id",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 3,
            },
            OutputEdge {
                to: "memory_id_to_big",
                word_base: 10,
                words_per_instance: 1,
                n_instances: 3,
            },
            OutputEdge {
                to: "verify_instruction",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
        ],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "cube_252",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[],
        counts: &[
            CountFeed {
                family: "range_check_20_state",
                n_relations: 8,
            },
            CountFeed {
                family: "range_check_9_9_state",
                n_relations: 8,
            },
        ],
        slots: None,
    },
    ComponentNode {
        id: "jnz_opcode_non_taken",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[
            OutputEdge {
                to: "memory_address_to_id",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 1,
            },
            OutputEdge {
                to: "memory_id_to_big",
                word_base: 8,
                words_per_instance: 1,
                n_instances: 1,
            },
            OutputEdge {
                to: "verify_instruction",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
        ],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "jnz_opcode_taken",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[
            OutputEdge {
                to: "memory_address_to_id",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 2,
            },
            OutputEdge {
                to: "memory_id_to_big",
                word_base: 9,
                words_per_instance: 1,
                n_instances: 2,
            },
            OutputEdge {
                to: "verify_instruction",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
        ],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "jump_opcode_abs",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[
            OutputEdge {
                to: "memory_address_to_id",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 1,
            },
            OutputEdge {
                to: "memory_id_to_big",
                word_base: 8,
                words_per_instance: 1,
                n_instances: 1,
            },
            OutputEdge {
                to: "verify_instruction",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
        ],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "jump_opcode_double_deref",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[
            OutputEdge {
                to: "memory_address_to_id",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 2,
            },
            OutputEdge {
                to: "memory_id_to_big",
                word_base: 9,
                words_per_instance: 1,
                n_instances: 2,
            },
            OutputEdge {
                to: "verify_instruction",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
        ],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "jump_opcode_rel",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[
            OutputEdge {
                to: "memory_address_to_id",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 1,
            },
            OutputEdge {
                to: "memory_id_to_big",
                word_base: 8,
                words_per_instance: 1,
                n_instances: 1,
            },
            OutputEdge {
                to: "verify_instruction",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
        ],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "jump_opcode_rel_imm",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[
            OutputEdge {
                to: "memory_address_to_id",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 1,
            },
            OutputEdge {
                to: "memory_id_to_big",
                word_base: 8,
                words_per_instance: 1,
                n_instances: 1,
            },
            OutputEdge {
                to: "verify_instruction",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
        ],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "memory_address_to_id",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[
            InputEdge::Producer {
                of: "add_ap_opcode",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "add_opcode",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 3,
            },
            InputEdge::Producer {
                of: "add_opcode_small",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 3,
            },
            InputEdge::Producer {
                of: "assert_eq_opcode",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 2,
            },
            InputEdge::Producer {
                of: "assert_eq_opcode_double_deref",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 3,
            },
            InputEdge::Producer {
                of: "assert_eq_opcode_imm",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 2,
            },
            InputEdge::Producer {
                of: "blake_round",
                word_base: 49,
                words_per_instance: 1,
                n_instances: 16,
            },
            InputEdge::Producer {
                of: "call_opcode_abs",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 3,
            },
            InputEdge::Producer {
                of: "call_opcode_rel_imm",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 3,
            },
            InputEdge::Producer {
                of: "jnz_opcode_non_taken",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "jnz_opcode_taken",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 2,
            },
            InputEdge::Producer {
                of: "jump_opcode_abs",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "jump_opcode_double_deref",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 2,
            },
            InputEdge::Producer {
                of: "jump_opcode_rel",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "jump_opcode_rel_imm",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "mul_opcode",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 3,
            },
            InputEdge::Producer {
                of: "mul_opcode_small",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 3,
            },
            InputEdge::Producer {
                of: "qm_31_add_mul_opcode",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 3,
            },
            InputEdge::Producer {
                of: "ret_opcode",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 2,
            },
            InputEdge::Producer {
                of: "verify_instruction",
                word_base: 5,
                words_per_instance: 1,
                n_instances: 1,
            },
        ],
        outputs: &[],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "memory_id_to_big",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[
            InputEdge::Producer {
                of: "add_ap_opcode",
                word_base: 8,
                words_per_instance: 1,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "add_opcode",
                word_base: 10,
                words_per_instance: 1,
                n_instances: 3,
            },
            InputEdge::Producer {
                of: "add_opcode_small",
                word_base: 10,
                words_per_instance: 1,
                n_instances: 3,
            },
            InputEdge::Producer {
                of: "assert_eq_opcode_double_deref",
                word_base: 10,
                words_per_instance: 1,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "blake_round",
                word_base: 65,
                words_per_instance: 1,
                n_instances: 16,
            },
            InputEdge::Producer {
                of: "call_opcode_abs",
                word_base: 10,
                words_per_instance: 1,
                n_instances: 3,
            },
            InputEdge::Producer {
                of: "call_opcode_rel_imm",
                word_base: 10,
                words_per_instance: 1,
                n_instances: 3,
            },
            InputEdge::Producer {
                of: "jnz_opcode_non_taken",
                word_base: 8,
                words_per_instance: 1,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "jnz_opcode_taken",
                word_base: 9,
                words_per_instance: 1,
                n_instances: 2,
            },
            InputEdge::Producer {
                of: "jump_opcode_abs",
                word_base: 8,
                words_per_instance: 1,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "jump_opcode_double_deref",
                word_base: 9,
                words_per_instance: 1,
                n_instances: 2,
            },
            InputEdge::Producer {
                of: "jump_opcode_rel",
                word_base: 8,
                words_per_instance: 1,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "jump_opcode_rel_imm",
                word_base: 8,
                words_per_instance: 1,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "mul_opcode",
                word_base: 10,
                words_per_instance: 1,
                n_instances: 3,
            },
            InputEdge::Producer {
                of: "mul_opcode_small",
                word_base: 10,
                words_per_instance: 1,
                n_instances: 3,
            },
            InputEdge::Producer {
                of: "pedersen_aggregator_window_bits_18",
                word_base: 0,
                words_per_instance: 1,
                n_instances: 3,
            },
            InputEdge::Producer {
                of: "qm_31_add_mul_opcode",
                word_base: 10,
                words_per_instance: 1,
                n_instances: 3,
            },
            InputEdge::Producer {
                of: "ret_opcode",
                word_base: 9,
                words_per_instance: 1,
                n_instances: 2,
            },
            InputEdge::Producer {
                of: "verify_instruction",
                word_base: 6,
                words_per_instance: 1,
                n_instances: 1,
            },
        ],
        outputs: &[],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "mul_opcode",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[
            OutputEdge {
                to: "memory_address_to_id",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 3,
            },
            OutputEdge {
                to: "memory_id_to_big",
                word_base: 10,
                words_per_instance: 1,
                n_instances: 3,
            },
            OutputEdge {
                to: "verify_instruction",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
        ],
        counts: &[CountFeed {
            family: "range_check_20_state",
            n_relations: 8,
        }],
        slots: None,
    },
    ComponentNode {
        id: "mul_opcode_small",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[
            OutputEdge {
                to: "memory_address_to_id",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 3,
            },
            OutputEdge {
                to: "memory_id_to_big",
                word_base: 10,
                words_per_instance: 1,
                n_instances: 3,
            },
            OutputEdge {
                to: "verify_instruction",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
        ],
        counts: &[CountFeed {
            family: "range_check_11_state",
            n_relations: 1,
        }],
        slots: None,
    },
    ComponentNode {
        id: "partial_ec_mul_generic",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[],
        counts: &[
            CountFeed {
                family: "range_check_20_state",
                n_relations: 8,
            },
            CountFeed {
                family: "range_check_8_state",
                n_relations: 1,
            },
            CountFeed {
                family: "range_check_9_9_state",
                n_relations: 8,
            },
        ],
        slots: None,
    },
    ComponentNode {
        id: "partial_ec_mul_window_bits_18",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[InputEdge::Producer {
            of: "pedersen_aggregator_window_bits_18",
            word_base: 7,
            words_per_instance: 72,
            n_instances: 28,
        }],
        outputs: &[],
        counts: &[
            CountFeed {
                family: "pedersen_points_table_window_bits_18_state",
                n_relations: 1,
            },
            CountFeed {
                family: "range_check_20_state",
                n_relations: 8,
            },
            CountFeed {
                family: "range_check_9_9_state",
                n_relations: 8,
            },
        ],
        slots: None,
    },
    ComponentNode {
        id: "pedersen_aggregator_window_bits_18",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[
            OutputEdge {
                to: "memory_id_to_big",
                word_base: 0,
                words_per_instance: 1,
                n_instances: 3,
            },
            OutputEdge {
                to: "partial_ec_mul_window_bits_18",
                word_base: 7,
                words_per_instance: 72,
                n_instances: 28,
            },
        ],
        counts: &[CountFeed {
            family: "range_check_8_state",
            n_relations: 1,
        }],
        slots: None,
    },
    ComponentNode {
        id: "qm_31_add_mul_opcode",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[
            OutputEdge {
                to: "memory_address_to_id",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 3,
            },
            OutputEdge {
                to: "memory_id_to_big",
                word_base: 10,
                words_per_instance: 1,
                n_instances: 3,
            },
            OutputEdge {
                to: "verify_instruction",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
        ],
        counts: &[CountFeed {
            family: "range_check_4_4_4_4_state",
            n_relations: 1,
        }],
        slots: None,
    },
    ComponentNode {
        id: "range_check_252_width_27",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[],
        counts: &[
            CountFeed {
                family: "range_check_18_state",
                n_relations: 2,
            },
            CountFeed {
                family: "range_check_9_9_state",
                n_relations: 5,
            },
        ],
        slots: None,
    },
    ComponentNode {
        id: "range_check_4_3",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[InputEdge::Producer {
            of: "verify_instruction",
            word_base: 3,
            words_per_instance: 2,
            n_instances: 1,
        }],
        outputs: &[],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "ret_opcode",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[
            OutputEdge {
                to: "memory_address_to_id",
                word_base: 7,
                words_per_instance: 1,
                n_instances: 2,
            },
            OutputEdge {
                to: "memory_id_to_big",
                word_base: 9,
                words_per_instance: 1,
                n_instances: 2,
            },
            OutputEdge {
                to: "verify_instruction",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
        ],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "triple_xor_32",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[],
        outputs: &[OutputEdge {
            to: "verify_bitwise_xor_8",
            word_base: 0,
            words_per_instance: 3,
            n_instances: 8,
        }],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "verify_bitwise_xor_12",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[InputEdge::Producer {
            of: "blake_g",
            word_base: 24,
            words_per_instance: 3,
            n_instances: 2,
        }],
        outputs: &[],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "verify_bitwise_xor_4",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[InputEdge::Producer {
            of: "blake_g",
            word_base: 30,
            words_per_instance: 3,
            n_instances: 2,
        }],
        outputs: &[],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "verify_bitwise_xor_7",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[InputEdge::Producer {
            of: "blake_g",
            word_base: 36,
            words_per_instance: 3,
            n_instances: 2,
        }],
        outputs: &[],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "verify_bitwise_xor_8",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[
            InputEdge::Producer {
                of: "blake_g",
                word_base: 0,
                words_per_instance: 3,
                n_instances: 8,
            },
            InputEdge::Producer {
                of: "triple_xor_32",
                word_base: 0,
                words_per_instance: 3,
                n_instances: 8,
            },
        ],
        outputs: &[],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "verify_bitwise_xor_9",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[InputEdge::Producer {
            of: "blake_g",
            word_base: 42,
            words_per_instance: 3,
            n_instances: 2,
        }],
        outputs: &[],
        counts: &[],
        slots: None,
    },
    ComponentNode {
        id: "verify_instruction",
        kernel: None,
        log_size: LogSizeSource::FromStates,
        inputs: &[
            InputEdge::Producer {
                of: "add_ap_opcode",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "add_opcode",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "add_opcode_small",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "assert_eq_opcode",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "assert_eq_opcode_double_deref",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "assert_eq_opcode_imm",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "call_opcode_abs",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "call_opcode_rel_imm",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "jnz_opcode_non_taken",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "jnz_opcode_taken",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "jump_opcode_abs",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "jump_opcode_double_deref",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "jump_opcode_rel",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "jump_opcode_rel_imm",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "mul_opcode",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "mul_opcode_small",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "qm_31_add_mul_opcode",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
            InputEdge::Producer {
                of: "ret_opcode",
                word_base: 0,
                words_per_instance: 7,
                n_instances: 1,
            },
        ],
        outputs: &[
            OutputEdge {
                to: "memory_address_to_id",
                word_base: 5,
                words_per_instance: 1,
                n_instances: 1,
            },
            OutputEdge {
                to: "memory_id_to_big",
                word_base: 6,
                words_per_instance: 1,
                n_instances: 1,
            },
            OutputEdge {
                to: "range_check_4_3",
                word_base: 3,
                words_per_instance: 2,
                n_instances: 1,
            },
        ],
        counts: &[CountFeed {
            family: "range_check_7_2_5_state",
            n_relations: 1,
        }],
        slots: None,
    },
];
